apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-config
  namespace: iot
data:
  DB_HOST: "db-cluster-rw"
  DB_NAME: "votedb"
  DB_PORT: "5432"
  BACKEND_PORT: "8080"
  NEXT_PUBLIC_BACKEND_URL: "/api"
