apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        # hostsプラグインの設定を修正
        hosts {
          # 解決させたいドメインをここに明示的に書く
          192.168.56.110 kaisobes kaisobeS gitlab.k8s.icchon.jp registry.k8s.icchon.jp minio.k8s.icchon.jp
          192.168.56.111 kaisobesw kaisobeSW
          # この一票が重要：定義されていないドメインを次に渡す
          fallthrough
        }
        prometheus :9153
        forward . 8.8.8.8
        cache 30
        loop
        reload
        loadbalance
    }
    