apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - image: icchondocker/vote-backend:v0.1.0
        name: vote-backend
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: DB_NAME
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: BACKEND_PORT
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-deployment
  name: backend-service
  namespace: dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: backend-deployment
  type: ClusterIP
