global:
  hosts:
    domain: k8s.icchon.jp
    gitlab:
      name: gitlab2.k8s.icchon.jp
      https: true
    registry:
      name: registry2.k8s.icchon.jp
    minio:
      name: minio2.k8s.icchon.jp
  ingress:
    configureCertmanager: true
    annotations:
      cert-manager.io/cluster-issuer: "cloudflare-issuer"
    enabled: true
    class: nginx
    tls:
      enabled: true

certmanager-issuer:
  install: false
  email: icchon1001@gmail.com

registry:
  enabled: true
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: "cloudflare-issuer"
    tls:
      enabled: true
      secretName: gitlab-registry-tls

# 2. リソースを大量に喰う「監視系」を徹底的にOFFにする
prometheus:
  install: false
gitlab-exporter:
  enabled: false
nginx-ingress:
  enabled: true
  controller:
    kind: Deployment
    scope:
      enabled: false
    service:
      type: LoadBalancer

# 3. GitLab本体（Rails/Sidekiq）の軽量化
gitlab:
  webservice:
    ingress:
      tls:
        secretName: gitlab-webservice-tls
    workerConfig:
      minProcesses: 2
      maxProcesses: 2
  sidekiq:
    concurrency: 5
  kas:
    enabled: false
  toolbox:
    replicas: 1

# 4. データベースとキャッシュ（最小構成)
postgresql:
  image:
    tag: 16.6.0
  primary:
    resources:
      requests:
        memory: 512Mi
redis:
  metrics:
    enabled: false

# 5. Runnerの設定（後で使う）
gitlab-runner:
  install: true
  runners:
    privileged: true
  command: ["run"]
  rbac:
    create: true
  hostAliases:
    - ip: "10.43.247.185"
      hostnames:
        - "gitlab2.k8s.icchon.jp"

