apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1-deployment
  name: app1-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-deployment
  template:
    metadata:
      labels:
        app: app1-deployment
    spec:
      containers:
      - image: registry.k8s.icchon.jp/root/iot/vote-app1:v0.2.0
        name: vote-app1
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: vote-config
              key: NEXT_PUBLIC_BACKEND_URL
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app1-deployment
  name: app1-service
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: app1-deployment
  type: ClusterIP
