apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: iot-cluster
servers: 1
agents: 1
image: rancher/k3s:v1.30.4-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  config: |
    configs:
      "registry.k8s.icchon.jp":
        tls:
          insecure_skip_verify: true
