Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false

  # --- Master Node (GitLab + K3s Server) ---
  config.vm.define "kaisobeS" do |s|
    s.vm.hostname = "kaisobeS"
    s.vm.network "private_network", ip: "192.168.56.110"
    s.vm.provider "virtualbox" do |vb|
      vb.memory = "16384" 
      vb.cpus = 4
      vb.customize ["modifyvm", :id, "--vram", "128"]
    end
    s.vm.provision "shell", path: "scripts/setup_server.sh"
    s.vm.provision "shell", inline: <<-SHELL
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl restart ssh
    SHELL
  end

  # --- Worker Node ---
  config.vm.define "kaisobeSW" do |sw|
    sw.vm.hostname = "kaisobeSW"
    sw.vm.network "private_network", ip: "192.168.56.111"
    sw.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 2
    end
    sw.vm.provision "shell", path: "scripts/setup_worker.sh"
  end
end
