apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db-cluster
spec:
  instances: 3

  bootstrap:
    initdb:
      database: votedb
      owner: user
      secret:
        name: db-secret
  storage:
    size: 1Gi
