apiVersion: v1
kind: Service
metadata:
  labels:
    app: app3-deployment
  name: app3-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: app3-deployment
status:
  loadBalancer: {}
